"""teacher synced with subject taught

Revision ID: 1acc0baf9e71
Revises: 8eb9206ba995
Create Date: 2026-04-21 22:27:06.670199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acc0baf9e71'
down_revision: Union[str, Sequence[str], None] = '8eb9206ba995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
