"""synced teacehr_subjects

Revision ID: 1f3ea32aa5a4
Revises: 12ecb458f109
Create Date: 2026-04-21 22:57:02.193685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3ea32aa5a4'
down_revision: Union[str, Sequence[str], None] = '12ecb458f109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
