"""add student_subject marks and teacher_subject_students

Revision ID: 598f236c3d83
Revises: 1f3ea32aa5a4
Create Date: 2026-04-21 23:56:52.690059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598f236c3d83'
down_revision: Union[str, Sequence[str], None] = '1f3ea32aa5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subject_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_subject_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Float(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_subject_id'], ['teacher_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_subject_id', 'student_id', name='uq_teacher_subject_student')
    )
    op.create_index(op.f('ix_teacher_subject_students_id'), 'teacher_subject_students', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_students_student_id'), 'teacher_subject_students', ['student_id'], unique=False)
    op.create_index(op.f('ix_teacher_subject_students_teacher_subject_id'), 'teacher_subject_students', ['teacher_subject_id'], unique=False)
    op.add_column('student_subjects', sa.Column('marks', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_subjects', 'marks')
    op.drop_index(op.f('ix_teacher_subject_students_teacher_subject_id'), table_name='teacher_subject_students')
    op.drop_index(op.f('ix_teacher_subject_students_student_id'), table_name='teacher_subject_students')
    op.drop_index(op.f('ix_teacher_subject_students_id'), table_name='teacher_subject_students')
    op.drop_table('teacher_subject_students')
    # ### end Alembic commands ###
