"""persisted refresh tokens

Revision ID: 8eb9206ba995
Revises: c6fde2db1fca
Create Date: 2026-04-21 12:42:31.905666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb9206ba995'
down_revision: Union[str, Sequence[str], None] = 'c6fde2db1fca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('refresh_jti', sa.String(), nullable=True))
    op.add_column('admins', sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_admins_refresh_jti'), 'admins', ['refresh_jti'], unique=True)
    op.add_column('students', sa.Column('refresh_jti', sa.String(), nullable=True))
    op.add_column('students', sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_students_refresh_jti'), 'students', ['refresh_jti'], unique=True)
    op.add_column('teachers', sa.Column('refresh_jti', sa.String(), nullable=True))
    op.add_column('teachers', sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_teachers_refresh_jti'), 'teachers', ['refresh_jti'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teachers_refresh_jti'), table_name='teachers')
    op.drop_column('teachers', 'refresh_expires_at')
    op.drop_column('teachers', 'refresh_jti')
    op.drop_index(op.f('ix_students_refresh_jti'), table_name='students')
    op.drop_column('students', 'refresh_expires_at')
    op.drop_column('students', 'refresh_jti')
    op.drop_index(op.f('ix_admins_refresh_jti'), table_name='admins')
    op.drop_column('admins', 'refresh_expires_at')
    op.drop_column('admins', 'refresh_jti')
    # ### end Alembic commands ###
